export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SEI_PRODUCTS = 'SEI_PRODUCTS';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT'